basic:
    name: 'https://www.side.com/success-stories/how-it-should-be-done'
    environments:
        production: 'https://www.side.com/success-stories/how-it-should-be-done'
        staging: ''
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: { user: '', password: '' }
    breakpoints:
        - 1200
    pages:
        - /
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: 'iframe[src*="vidyard"]'
    remove: ''
    delay: 15
    scroll: false
    headers:
        - { value: '', header: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { type: title, selector: '' }
    sensitivity: 15
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: false
