basic:
    name: 'https://www.side.com/success-stories/how-it-should-be-done'
    environments:
        production: 'https://www.side.com/success-stories/how-it-should-be-done'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 760
        - 768
        - 1024
        - 1080
        - 1200
        - 1920
    pages:
        - /
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ".vidyard-player-container\n.case-study-video"
    isolate: ''
    delay: 15
    scroll: false
    headers:
        - { value: '', header: '' }
    cookies: ''
    custom_js: ''
    custom_css: ".case-study-video {\n\tmargin-top: 0px !important;\n    margin-bottom: 0px !important;\n  \tpadding: 0 !important;\n     height: 300px !important\n}\n\n.vidyard-player-container {\n    display: block !important;\n  \tposition: unset !important;\n}\n\n.vidyard-div-1PnWrpaADpW9hNYBY1euch {\n    position: unset !important; \n}"
    mock_content:
        - { type: title, selector: '' }
    sensitivity: 15
    night_mode: false
    retina_images: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
proxy: false
type: single-site
